select * from customer 
select count(*) from customer

--Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender


--Q2. Which customers used a discount but still spent more than the average purchase amount? 
WITH avg_val AS (
    SELECT AVG(purchase_amount) AS avg_amt FROM customer
)
SELECT customer_id, purchase_amount
FROM customer, avg_val
WHERE discount_applied = 'Yes'
AND purchase_amount > avg_amt;

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, 
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(AVG(CASE WHEN discount_applied = 'Yes' THEN 1.0 ELSE 0 END)*100,2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 


SELECT 
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
END AS segment,
COUNT(*) 
FROM customer
GROUP BY segment;


--Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;
 
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;


--Q11. Which age group spends the most per order?
SELECT age_group,
       ROUND(AVG(purchase_amount),2) AS avg_spend
FROM customer
GROUP BY age_group
ORDER BY avg_spend DESC;


--Q12.Which category generates highest revenue?

Select category, sum(purchase_amount) as category_revenue
FROM customer
GROUP BY category
ORDER BY category_revenue DESC

--Q13. Which location generates the highest revenue?
SELECT 
    location,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY location
ORDER BY total_revenue DESC;

--Q14.Which season has the highest sales?

SELECT 
    season,
    SUM(purchase_amount) AS total_revenue,
    COUNT(*) AS total_orders
FROM customer
GROUP BY season
ORDER BY total_revenue DESC;

--Q15.Which category performs best by revenue and orders?
SELECT 
    category,
    COUNT(*) AS total_orders,
    SUM(purchase_amount) AS total_revenue,
    ROUND(AVG(purchase_amount),2) AS avg_order_value
FROM customer
GROUP BY category
ORDER BY total_revenue DESC;


--Q16.Which payment method is used most?
SELECT 
    payment_method,
    COUNT(*) AS total_orders,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY payment_method
ORDER BY total_orders DESC; 

--Q17.Which size is most popular in each category?
With size_rank AS(
	SELECT category,size,COUNT(*) AS total_orders,
		RANK() OVER(PARTITION BY category
		ORDER by COUNT(*) DESC)AS rnk 
	FROM customer
	GROUP BY category,size
)
SELECT category, size, total_orders
FROM size_rank
WHERE rnk = 1;

--Q18.Which colors are most purchased?
SELECT 
    color,
    COUNT(*) AS total_orders,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY color
ORDER BY total_orders DESC
LIMIT 10;

--Q19. Which items have high rating but low revenue?

SELECT 
    item_purchased,
    ROUND(AVG(review_rating)::numeric,2) AS avg_rating,
    SUM(purchase_amount) AS total_revenue,
    COUNT(*) AS total_orders
FROM customer
GROUP BY item_purchased
HAVING AVG(review_rating) >= 3.5
ORDER BY total_revenue ASC;